baseURL = "https://vipau.dev"
canonifyURLs = true
title = "Vi Pau"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = false

[pagination]
pagerSize = 8

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "Vi Pau"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Linux enthusiast, specialist and SRE with a deep passion for simple setups that are reliable and powerful"
keywords = "blog,sysadmin,linux,sre,personal"
info = ["Linux Specialist & SRE", "System Sorceress"]
avatarURL = "images/avatar.jpg"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2020
# Right To Left, shift content direction for languages such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "dark"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = ["custom.css"]
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

[taxonomies]
tag = "tags"
series = "series"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 1
url = "https://www.linkedin.com/in/vipau/"

[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github fa-2x"
weight = 3
url = "https://github.com/vipau/"

[[params.social]]
name = "Stack Exchange Network Profile"
icon = "fa-brands fa-stack-exchange fa-2x"
weight = 5
url = "https://stackexchange.com/users/1498720/vi-pau?tab=accounts"

[[params.social]]
name = "Email"
icon = "fa-solid fa-envelope fa-2x"
weight = 9
url = "mailto:me@vipau.dev"

[[params.social]]
name = "RSS"
icon = "fa-solid fa-rss fa-2x"
weight = 7
url = "/index.xml"
rel = "alternate"
type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"
